#!/usr/bin/env ruby

require 'revue'
require 'optparse'

OptionParser.new do |options|
  options.on '-c', '--config', 'Specify configuration file' do |config_file_path|
    Revue.config_path = config_file_path
  end
end.parse!

Revue.server.run
